### ISSUE TITLE
getting globus auth to work

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#101]
I am playing around with using globus for auth. I followed the instructions here:

https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#globus

My hub pod is giving this error

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1639, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 288, in <module>
        set_config_if_not_none(c.GlobusOAuthenticator, trait, 'auth.globus.' + cfg_key)
    TypeError: must be str, not NoneType
```

I think this is related to these issues and PRs:
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1167
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1171 (only 21 hours old!)

I wonder if @consideRatio can confirm that this is related to his recent PR.

If so, how do we point at the very latest chart?

**Comment by rabernat** [comment]
So #102 definitely got us closer. I was able to begin the authentication process with Globus. But I am now getting a new error, from Globus itself, after I get redirected there.

```
Unable to Fulfill Your Request
Error processing OAuth2 request
Sorry, but we encountered a problem while servicing your request.

Missing client_id parameter.
Occurred at time:
2019-03-02T05:49:36.154561+00:00
Error ID:
a8045c6211e249f1891c5f97059632d1
Error code:
OAUTH_AUTH_REQUEST_FAILURE
If this problem persists, please contact support and copy-paste the information above to help us resolve the problem.
```

In my secrets, I have

```yaml
jupyterhub:
  proxy:
    secretToken: XXX
  auth:
    type: globus
    github:
      clientId: "XXX"
      clientSecret: "XXX"
      callbackUrl: "https://staging.pangeo.io/hub/oauth_callback"
      identityProvider: "ORCID"
```

So I am using `clientId` instead of `client_id`. Maybe this is the problem?

**Comment by consideRatio** [comment]
I think I spotted a typo in the config above, as described here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1173#issuecomment-468912966

### Regarding the camelCase vs snake_case situation
Currently the Helm chart requires things written in camelCasing event though the underlying Authenticator classes use snake_casing.

```yaml
auth:
  type: globus
  globus:
    thisShouldBeCamelCase: "but i want it to support either or in the future, remaining backward compatible while not changing the case used to configure the actual traitlet with snake_casing."
    clientId: "this will configure client_id currently"
```

**Comment by rabernat** [comment]
Yes duh! That's why you shouldn't work on these things after midnight! Thanks so much for your help. Now on to the next error! :)
