### ISSUE TITLE
get-commit-range.py is failing on PR builds

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#157]
This seems to be a replay of #52! I thought we squashed this with #54?

```
#!/bin/bash -eo pipefail
# CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
COMMIT_RANGE=$(./.circleci/get-commit-range.py)
echo ${COMMIT_RANGE}
echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}
Traceback (most recent call last):
  File "./.circleci/get-commit-range.py", line 90, in <module>
    main()
  File "./.circleci/get-commit-range.py", line 84, in main
    print(from_branch(args.project, args.repo, branch_name))
  File "./.circleci/get-commit-range.py", line 29, in from_branch
    raise ValueError(f'No PR from branch {branch_name} in upstream repo found')
ValueError: No PR from branch tweak-docker in upstream repo found
Exited with code 1
```

cc @yuvipanda

**Comment by yuvipanda** [comment]
We only fixed it for deployments, not builds. I never actually got around to making the images public and fixing it for builds. Oops...

**Comment by yuvipanda** [comment]
Also, this only happens if you are making a PR from the same repo, right?
