### ISSUE TITLE
notebook pod complains jupyter is not installed

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#158]
I have replaced the ocean image with a passthrough docker file
https://github.com/pangeo-data/pangeo-cloud-federation/blob/78f5f9f118565cd72d121621da6cf2f41f4d9d77/deployments/ocean/image/binder/Dockerfile#L1-L2

That image lives over in https://github.com/pangeo-data/pangeo-stacks, where it is built by repo2docker. It is already being used by binder via https://github.com/pangeo-data/pangeo_ocean_examples/ in a similar way, and it seems to work.

However, here the notebook pod won't start, and I get these errors:
```
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/jupyterlab/labhubapp.py", line 5, in <module>
    from jupyterhub.singleuser import SingleUserNotebookApp
ModuleNotFoundError: No module named 'jupyterhub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/bin/jupyter-labhub", line 7, in <module>
    from jupyterlab.labhubapp import main
  File "/srv/conda/lib/python3.6/site-packages/jupyterlab/labhubapp.py", line 8, in <module>
    raise ImportError('You must have jupyterhub installed for this to work.')
ImportError: You must have jupyterhub installed for this to work.
```

What is going on here?

**Comment by rabernat** [comment]
From Yuvi on gitter:

> you need to do a 'pip install jupyterhub==0.9.4' - however, that should already be done by repo2docker for you. If you can launch the image in binder, can you check if 'pip freeze' lists jupyterhub?
running on binder only requires the 'notebook' package, while jupyterhub requires the jupyterhub package

**Comment by rabernat** [comment]
```
> pip freeze
affine==2.2.2
appdirs==1.4.3
asciitree==0.3.3
asn1crypto==0.24.0
attrs==18.2.0
backcall==0.1.0
basemap==1.2.0
bleach==3.1.0
blinker==1.4
blosc==1.8.1
bokeh==1.0.4
cachetools==2.1.0
Cartopy==0.17.0
certifi==2019.3.9
cffi==1.12.2
cftime==1.0.3.4
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
cloudpickle==0.8.0
cmocean==2.0
colorcet==1.0.0
conda==4.6.8
configobj==5.0.6
cryptography==2.5
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.1.4
dask-kubernetes==0.7.0
dask-labextension==0.3.1
datashader==0.6.9a1
datashape==0.5.4
decorator==4.3.2
defusedxml==0.5.0
descartes==1.1.0
distributed==1.26.0
docrep==0.2.5
entrypoints==0.3
fasteners==0.14.1
Fiona==1.8.4
future==0.17.1
gcsfs==0.2.1
GDAL==2.4.0
geopandas==0.4.1
geoviews==1.6.3a2
google-auth==1.6.3
google-auth-oauthlib==0.1.0
graphviz==0.10.1
gsw==3.3.0
heapdict==1.0.0
holoviews==1.11.2a1
hvplot==0.3.0
idna==2.8
imageio==2.5.0
intake==0.4.2+11.gd3d7da7
intake-xarray==0.3.0
ipaddress==1.0.22
ipykernel==5.1.0
ipython==7.1.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-launcher==0.13.1
jupyterlab-server==0.2.0
kiwisolver==1.0.1
kubernetes==4.0.0
llvmlite==0.26.0
locket==0.2.0
lxml==4.3.2
lz4==2.1.6
mapclassify==2.0.1
Markdown==2.6.11
MarkupSafe==1.1.1
matplotlib==3.0.3
MetPy==0.10.0
mistune==0.8.4
monotonic==1.5
msgpack==0.6.1
msgpack-numpy==0.4.4.2
msgpack-python==0.5.6
multipledispatch==0.6.0
munch==2.3.2
nbconvert==5.4.0
nbformat==4.4.0
nbgitpuller==0.6.1
nbserverproxy==0.8.8
netCDF4==1.4.3.2
networkx==2.2
notebook==5.7.5
numba==0.41.0
numcodecs==0.6.3
numpy==1.15.2
oauthlib==3.0.1
olefile==0.46
OWSLib==0.17.1
packaging==19.0
pandas==0.24.1
pandocfilters==1.4.2
panel==0.3.1
param==1.8.2
parso==0.3.3
partd==0.3.9
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
Pint==0.9
pooch==0.2.1
prometheus-client==0.5.0
prompt-toolkit==2.0.8
psutil==5.5.1
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.4
pycosat==0.6.3
pycparser==2.19
pyct==0.4.6
pyepsg==0.4.0
Pygments==2.3.1
PyJWT==1.7.1
pykdtree==1.3.1
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyproj==1.9.6
pyresample==1.10.3
pyrsistent==0.14.11
pyshp==2.1.0
PySocks==1.6.8
python-dateutil==2.8.0
python-snappy==0.5.3
pytz==2018.9
pyviz-comms==0.7.0
PyWavelets==1.0.2
PyYAML==3.13
pyzmq==18.0.1
qtconsole==4.4.3
rasterio==1.0.21
requests==2.21.0
requests-oauthlib==0.8.0
rsa==3.4.2
Rtree==0.8.3
ruamel-yaml==0.15.71
scikit-image==0.14.2
scipy==1.1.0
Send2Trash==1.5.0
Shapely==1.6.4.post2
six==1.12.0
snuggs==1.4.3
sortedcontainers==2.1.0
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.40.0
widgetsnbextension==3.4.2
xarray==0.11.1+69.gc770eec3
xgcm==0.1.0
zarr==2.2.1.dev146
zict==0.1.4
```

No jupyterhub
