### ISSUE TITLE
recent helm upgrades failing with "Error: DaemonSet with already exists"

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#355]
Logs from circleci:

```
Activated service account credentials for: [hubploy-circleci@pangeo-181919.iam.gserviceaccount.com]
WARNING: Accessing a Kubernetes Engine cluster requires the kubernetes commandline
client [kubectl]. To install, run
  $ gcloud components install kubectl

Fetching cluster endpoint and auth data.
kubeconfig entry generated for dev-pangeo-io-cluster.
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
UPGRADE FAILED
Error: kind DaemonSet with the name "continuous-image-puller" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind DaemonSet with the name "continuous-image-puller" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 65, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 128, in deploy
    version
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 58, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'hydro-prod', 'hydro-prod', 'pangeo-deploy', '-f', 'deployments/hydro/config/common.yaml', '-f', 'deployments/hydro/config/prod.yaml', '-f', 'deployments/hydro/secrets/prod.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=30cfa3e', '--set', 'pangeo.jupyterhub.singleuser.image.name=us.gcr.io/pangeo-181919/hydro-pangeo-io-notebook']' returned non-zero exit status 1.
```

Not sure why this is coming up now, but we did recently go from Helm 2.12 to Helm 2.14. Running `kubectl delete daemonset continuous-image-puller -n hydro-prod` and then re-deploying seems to fix it.

**Comment by tjcrone** [comment]
@rabernat and I ran into that [here](https://github.com/pangeo-data/pangeo-cloud-federation/pull/331), but it only happened after one failed release. We fixed it by rolling back to the latest successful release and tried the workflow again. I think a varietal of confusionals is possible with helm when a release fails. Deleting things is one solution. A rollback is probably the cleanest.

**Comment by scottyhq** [comment]
thanks for the note @tjcrone - i suspect you are right about the previous failed deploy and it's better to do a helm rollback than to delete things with kubectl. This other related issue also seems linked to a failed helm upgrade: https://github.com/pangeo-data/pangeo-cloud-federation/issues/353

**Comment by jhamman** [comment]
@scottyhq - did this get sorted out or do we have some more work to do here?

**Comment by scottyhq** [comment]
We can close this one but will keep #353 open.
