### ISSUE TITLE
Authentication errors on CircleCI/GCP

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo-cloud-federation#39]
I set up things according to the README, and still getting an authentication error on CircleCI in the "Build primary image if needed", when it is trying to run `hubploy-image-builder`: 

```
#!/bin/bash -eo pipefail
hubploy-image-builder \
  --push \
  --registry-url https://us.gcr.io \
  --registry-username _json_key \
  --registry-password "${GCR_READWRITE_KEY}" \
  --repo2docker \
  deployments/${DEPLOYMENT}/image/ ${IMAGE_NAME}
Traceback (most recent call last):
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/root/repo/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://35.237.221.205:2376/v1.35/distribution/us.gcr.io/learning-2-learn-221016/example-pangeo-io-notebook:2b306e1/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy-image-builder", line 11, in <module>
    load_entry_point('hubploy==0.1.0', 'console_scripts', 'hubploy-image-builder')()
  File "/root/repo/venv/lib/python3.6/site-packages/hubploy/imagebuilder.py", line 151, in main
    if needs_building(client, args.path, args.image_name):
  File "/root/repo/venv/lib/python3.6/site-packages/hubploy/imagebuilder.py", line 22, in needs_building
    image_manifest = client.images.get_registry_data(image_spec)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/models/images.py", line 333, in get_registry_data
    attrs=self.client.api.inspect_distribution(name),
  File "/root/repo/venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/image.py", line 266, in inspect_distribution
    self._get(self._url("/distribution/{0}/json", image)), True
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")
Exited with code 1
```

Do I need to edit the `secrets/staging.yaml` file in some way? I am using my own GCP account, not the one y'all have, so maybe that's the issue?

**Comment by darothen** [comment]
Bumping this issue... I'm running into the same issue using the bleeding edge of `hubploy` off of GitHub, with the much simpler command

``` shell
$ hubploy build <environment> --check-registry
```

I can build images just fine, but I can't check Container Registry. To test that, I followed the [Quickstart for Container Registry](https://cloud.google.com/container-registry/docs/quickstart) to upload an image at **us.gcr.io/<PROJECT>/quickstart-image:tag1**, but the following with the Python docker library fails:

``` python
import docker
client = docker.from_env()
client.images.get_registry_data("us.gcr.io/<PROJECT>/quickstart-image:tag1")
```
```
APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")
```

That's the command at the heart of `hubploy`. My service account should be configured just fine, and I have a key referenced by **hubploy.yaml**. Perhaps there's a configuration detail that isn't matriculating through?

**Comment by darothen** [comment]
So... following the details [here](https://cloud.google.com/container-registry/docs/access-control#serving_images_publicly), I made everything at the `us.gcr.io`host location public and BOOM it started working. I would love to learn about more secure solutions, though!
