### ISSUE TITLE
404 errors when opening dask dashboard on ocean.pangeo.io

### ISSUE THREAD

**Issue by cspencerjones** [pangeo-data/pangeo-cloud-federation#509]
Right now whenever I start a cluster on ocean.pangeo.io, I can't access the dask dashboard (I just get a "404 not found" Jupyterhub page when I click the link). @stb2145 is also having this problem. It is not clear to me what has changed, but any help would be appreciated!

**Comment by rabernat** [comment]
The problem is likely related to jupyter-server-proxy. Not sure why this would suddenly break.

**Comment by TomAugspurger** [comment]
Taking a look.

**Comment by shanicetbailey** [comment]
Thank you @cspencerjones for bringing this up.

**Comment by TomAugspurger** [comment]
I'm pretty stumped by this right now, but I think I've confirmed that jupyter-server-proxy isn't working properly.

On staging.hub.pangeo.io, where the dashboard is working, I can

1. Start a simple http server with `python -m http.server`
2. Make an authenticated request to the server via the proxy with `curl -H "Authorization: token <redacted>" https://staging.hub.pangeo.io/user/tomaugspurger/proxy/8000/` I manually created the API token.

The server gets the request and the client prints the right output.

On ocean.pangeo.io, repeating the same experiment (with the token & URL updated appropriately) prints nothing. The server doesn't get a request and the client doesn't print a response.

**Comment by TomAugspurger** [comment]
Ahh, this seems relevant

```
$  kubectl -n ocean-prod log jupyter-0000-2d0003-2d3651-2d396x
[W 2020-01-25 12:38:46.766 SingleUserNotebookApp notebookapp:1663] Error loading server extension jupyter_server_proxy
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/notebookapp.py", line 1658, in init_server_extensions
        func(self)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/__init__.py", line 27, in load_jupyter_server_extension
        server_proccesses += get_entrypoint_server_processes()
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/config.py", line 75, in get_entrypoint_server_processes
        make_server_process(entry_point.name, entry_point.load()())
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        self.require(*args, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2466, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (zipp 0.0.0 (/srv/conda/envs/notebook/lib/python3.7/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})
```

So we have an issue with the environment. Not sure why yet.

**Comment by TomAugspurger** [comment]
It's potentially jupyter_panel_proxy that's causing the issue.

```python

In [1]: from jupyter_server_proxy import get_entrypoint_server_processes                                                            

In [4]: get_entrypoint_server_processes()                                                                                           
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-4-28eab91d5a79> in <module>
----> 1 get_entrypoint_server_processes()

/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/config.py in get_entrypoint_server_processes()
     73     for entry_point in pkg_resources.iter_entry_points('jupyter_serverproxy_servers'):
     74         sps.append(
---> 75             make_server_process(entry_point.name, entry_point.load()())
     76         )
     77     return sps

/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py in load(self, require, *args, **kwargs)
   2441             )
   2442         if require:
-> 2443             self.require(*args, **kwargs)
   2444         return self.resolve()
   2445 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, env, installer)
   2464         # requirements for that extra are purely optional and skip over them.
   2465         reqs = self.dist.requires(self.extras)
-> 2466         items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2467         list(map(working_set.add, items))
   2468 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    790                 # Oops, the "best" so far conflicts with a dependency
    791                 dependent_req = required_by[req]
--> 792                 raise VersionConflict(dist, req).with_context(dependent_req)
    793 
    794             # push the new requirements onto the stack

ContextualVersionConflict: (zipp 0.0.0 (/srv/conda/envs/notebook/lib/python3.7/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})

In [5]: debug                                                                                                                       
> /srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py(792)resolve()
    790                 # Oops, the "best" so far conflicts with a dependency
    791                 dependent_req = required_by[req]
--> 792                 raise VersionConflict(dist, req).with_context(dependent_req)
    793 
    794             # push the new requirements onto the stack

ipdb> up                                                                                                                            
> /srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py(2466)require()
   2464         # requirements for that extra are purely optional and skip over them.
   2465         reqs = self.dist.requires(self.extras)
-> 2466         items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2467         list(map(working_set.add, items))
   2468 

ipdb> pp self                                                                                                                       
EntryPoint.parse('panel = panel_server:setup_panel_server')
ipdb> pp self.dist                                                                                                                  
jupyter-panel-proxy 0.1.0 (/srv/conda/envs/notebook/lib/python3.7/site-packages)
```

cc @jsignell if you have any guesses what the problem might be. I don't immediately see any issues.

**Comment by TomAugspurger** [comment]
I don't think jupyter_server_proxy is actually at fault here. The problem is likely that conda thinks it's installed `zipp 2.0.0`

```
(notebook) jovyan@jupyter-0000-2d0003-2d3651-2d396x:/srv/conda/envs/notebook/lib/python3.7/site-packages$ conda list zipp
# packages in environment at /srv/conda/envs/notebook:
#
# Name                    Version                   Build  Channel
zipp                      2.0.0                      py_0    conda-forge
```

when it's apparently zipp / pkg_resources / setuptools thinks it's 0.0.0

```
cat zipp-0.0.0.dist-info/
METADATA | grep Version
Metadata-Version: 2.1
Version: 0.0.0
```

**Comment by TomAugspurger** [comment]
Seems this is already know and fixed: https://github.com/conda-forge/zipp-feedstock/pull/10

So we just need to trigger a rebuild and I think things will work...

**Comment by TomAugspurger** [comment]
Things are working again as of https://app.circleci.com/jobs/github/pangeo-data/pangeo-cloud-federation/1036.

---

Just as an FYI @yuvipanda, a couple things that might have made this easier to debug :)

1. AFAICT, the output I tracked down in https://github.com/pangeo-data/pangeo-cloud-federation/issues/509#issuecomment-578403192 is only available to people with access to (and knowledge of) the kubernetes API. Is it sensible / possible to get the stdout of the container after it starts up, but (I think) before the notebook server is fully running? I'm a bit hazy on what starts up when, so I don't even know who would be capturing this stdout, but probably the notebook server?
2. Some logging from jupyter-server-proxy in `load_jupyter_server_extension` when it's starting up proxies. Is that sensible? If so I'll file an issue.

**Comment by rabernat** [comment]
Thanks so much Tom! We would be lost without you!

**Comment by jsignell** [comment]
Sorry I missed the ping on this one Tom! Glad you were able to figure it out.
