### ISSUE TITLE
Hubploy COMMIT_RANGE failing in this repo

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#52]
We have a CICD failure on CircleCI now:

```shell
#!/bin/bash -eo pipefail
# CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
COMMIT_RANGE=$(./.circleci/get-commit-range.py)
echo ${COMMIT_RANGE}
echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}
Traceback (most recent call last):
  File "./.circleci/get-commit-range.py", line 90, in <module>
    main()
  File "./.circleci/get-commit-range.py", line 84, in main
    print(from_branch(args.project, args.repo, branch_name))
  File "./.circleci/get-commit-range.py", line 29, in from_branch
    raise ValueError(f'No PR from branch {branch_name} in upstream repo found')
ValueError: No PR from branch staging in upstream repo found
Exited with code 1
```

I know @yuvipanda was mentioning this is a bit of a tricky part of the current setup. I think we just need someone to look into this and figure out what isn't working.

cc @rabernat and @raphaeldussin

**Comment by raphaeldussin** [comment]
The error seems to be coming from here:

https://github.com/berkeley-dsep-infra/datahub/blob/dbf9812cb3f0caf9e50ef94d6746698971f9eb20/.circleci/get-commit-range.py#L24

no pr.head.ref is equal to the branch name (= staging) so it fails.

```python

 In [1]: from github import Github

In [2]: gh = Github()

In [3]: prs = gh.get_repo(f'pangeo-data/dev.pangeo.io-deploy').get_pulls(state='all', sort='updated')

In [4]: prs
Out[4]: <github.PaginatedList.PaginatedList at 0x109299780>

In [5]: for pr in prs:
   ...:     print(pr.head.ref)
   ...:
rsignell-usgs-patch-1
rsignell-usgs-patch-1
rsignell-usgs-patch-2
rsignell-usgs-patch-3
rsignell-usgs-patch-1
rsignell-usgs-patch-2
rsignell-usgs-patch-1
rsignell-usgs-patch-1
fix/dask-worker-image
rsignell-usgs-patch-1
rsignell-usgs-patch-1
image_env_var
rsignell-usgs-patch-2
rsignell-usgs-patch-1
rsignell-usgs-patch-1
rsignell-usgs-patch-1
rsignell-usgs-patch-1
develop
develop
rsignell-usgs-patch-1
rsignell-usgs-patch-1
rsignell-usgs-patch-1
nfs_to_all
develop
ocean
develop
ocean-test
ocean-test
ocean-test
fix_40
ocean-test
revert-35-nfs_to_all
fix_40
per_hub_shared_fs

```

we need to somehow feed it with a PR that comes from staging/prod branches.

**Comment by raphaeldussin** [comment]
@rabernat @jhamman merging the PR from my fork on branch staging got us over the hump.
Now I am facing a permission denied error:

https://circleci.com/gh/pangeo-data/dev.pangeo.io-deploy/65

**Comment by jhamman** [comment]
@raphaeldussin - see #54. I think this will fix the conda install problem.

**Comment by rabernat** [comment]
So did #54 fix the problem?
