### ISSUE TITLE
New helm versions break ocean and dev

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#542]
We upgraded helm to 2.16.1 in the CI, and this worked fine in all of the staging deployments. But in production for ocean and dev, we now get:
```
Deleting outdated charts
UPGRADE FAILED
Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Get https://ooi-pangeo-ooi-pangeo-f5cc4e-950c76f4.hcp.eastus.azmk8s.io:443/apis/metrics.k8s.io/v1beta1?timeout=32s: context deadline exceeded
Error: UPGRADE FAILED: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Get https://ooi-pangeo-ooi-pangeo-f5cc4e-950c76f4.hcp.eastus.azmk8s.io:443/apis/metrics.k8s.io/v1beta1?timeout=32s: context deadline exceeded
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 89, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 129, in deploy
    force
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 65, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'ooi-prod', 'ooi-prod', 'pangeo-deploy', '--timeout', '1200', '-f', 'deployments/ooi/config/common.yaml', '-f', 'deployments/ooi/config/prod.yaml', '-f', 'deployments/ooi/secrets/prod.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=2c9911c', '--set', 'pangeo.jupyterhub.singleuser.image.name=ooicloud.azurecr.io/ooi-pangeo-io-notebook']' returned non-zero exit status 1.
{"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}
Exited with code exit status 1
CircleCI received exit code 1
```
These are the same errors we were getting in the OOI deployment with helm 2.14.3, so rolling back probably will not work. This issue has been [discussed at some length](https://github.com/helm/helm/issues/6361), but I'm not sure what the solution is for us. One thing we could do is use 2.14.3 for ocean and dev prod, but using two different versions of helm might not be super easy the way we have things set up. We could do a big refactor of the CI but that is a heavy lift. We could also use this as an opportunity to make the effort to get to helm3. Anyone have any suggestions for a quick fix or a more comprehensive fix? Thanks!

cc @yuvipanda, @jhamman, @scottyhq, @rabernat

**Comment by TomAugspurger** [comment]
It seems like upgrading to helm3 will fix this? Any objections to me messing with things to see if I can get that working?

**Comment by tjcrone** [comment]
I'm pretty sure we all want to get to helm3, so definitely +1 from me! Thanks Tom!

**Comment by tjcrone** [comment]
There are a few updates in hubploy related to helm3, including this one which is worth noting: https://github.com/yuvipanda/hubploy/commit/7c2f17389c27ee29582f2be005dfd6b3ab2d8db0.

**Comment by yuvipanda** [comment]
+1, I've switched almost everything I maintain to helm3! Definitely much better - the *actually useful* output from --debug alone is worth the price.

**Comment by TomAugspurger** [comment]
Currently failing to upgrade

```
$ env HELM_EXECUTABLE=/usr/local/bin/helm3 hubploy deploy dev pangeo-deploy staging
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "dask-gateway" chart repository
...Successfully got an update from the "dask" chart repository
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "pangeo" chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
Error: UPGRADE FAILED: cannot patch "gateway-dev-staging-dask-gateway" with kind Deployment: Deployment.apps "gateway-dev-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"gateway", "app.kubernetes.io/instance":"dev-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "scheduler-proxy-dev-staging-dask-gateway" with kind Deployment: Deployment.apps "scheduler-proxy-dev-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"scheduler-proxy", "app.kubernetes.io/instance":"dev-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "web-proxy-dev-staging-dask-gateway" with kind Deployment: Deployment.apps "web-proxy-dev-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"web-proxy", "app.kubernetes.io/instance":"dev-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Traceback (most recent call last):
  File "/Users/taugspurger/.virtualenvs/dask-dev/bin/hubploy", line 8, in <module>
    sys.exit(main())
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/hubploy/__main__.py", line 90, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/hubploy/helm.py", line 129, in deploy
    force
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/hubploy/helm.py", line 65, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/helm3', 'upgrade', '--wait', '--install', '--namespace', 'dev-staging', 'dev-staging', 'pangeo-deploy', '-f', 'deployments/dev/config/common.yaml', '-f', 'deployments/dev/config/staging.yaml', '-f', 'deployments/dev/secrets/staging.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=de4c2da', '--set', 'pangeo.jupyterhub.singleuser.image.name=gcr.io/pangeo-181919/dev-pangeo-io-notebook']' returned non-zero exit status 1.
```

It's the "Managed By" field that's changing from "Tiller" to "Helm"


```
$ helm3 get manifest dev-staging -n dev-staging --revision=443 | less 
...
  name: gateway-dev-staging-dask-gateway
  labels:
    app.kubernetes.io/name: dask-gateway
    helm.sh/chart: dask-gateway-0.6.1
    app.kubernetes.io/instance: dev-staging
    app.kubernetes.io/version: "0.6.1"
    app.kubernetes.io/managed-by: Tiller
```

vs

```
$ helm3 get manifest dev-staging -n dev-staging | less 
  name: gateway-dev-staging-dask-gateway
  labels:
    app.kubernetes.io/name: dask-gateway
    helm.sh/chart: dask-gateway-0.6.1
    app.kubernetes.io/instance: dev-staging
    app.kubernetes.io/version: "0.6.1"
    app.kubernetes.io/managed-by: Helm
```

investigating now...

**Comment by scottyhq** [comment]
@TomAugspurger - not sure this will help, but I documented the steps I took to move the AWS hubs to helm3 a while back here https://github.com/pangeo-data/pangeo-cloud-federation/pull/467#issuecomment-548115154

the `helm tiller` plugin in step 3) isn't needed if you have `helm3` installed.

**Comment by TomAugspurger** [comment]
Working off https://github.com/jetstack/cert-manager/issues/2451, it seems like something like this will work.

```
kubectl get deployment/gateway-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
```

rinse and repeat for all the problematic deployments. @yuvipanda can you maybe confirm that I won't blow things up with that? 😄 The current output of that is

```
$ kubectl get deployment/gateway-dev-staging-dask-gateway -n dev-staging -o yaml | grep Tiller
    app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/managed-by: Tiller
```

**Comment by TomAugspurger** [comment]
Decided to risk it (it's just dev-staging right 😄) and things seem ok...

```
$ kubectl get deployment/gateway-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/scheduler-proxy-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/web-proxy-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -

env HELM_EXECUTABLE=/usr/local/bin/helm3 hubploy deploy dev pangeo-deploy staging
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "dask-gateway" chart repository
...Successfully got an update from the "dask" chart repository
...Successfully got an update from the "pangeo" chart repository
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
Release "dev-staging" has been upgraded. Happy Helming!
NAME: dev-staging
LAST DEPLOYED: Thu Feb 13 11:53:54 2020
NAMESPACE: dev-staging
STATUS: deployed
REVISION: 447
TEST SUITE: None
```

**Comment by TomAugspurger** [comment]
OK, planning to do similar things to the rest of the staging deployments similarly. Then I'll make a PR to staging to use helm3 and see how that goes. If all looks well, I'll do the manual steps on prod, and then merge staging to prod.

Here are my rough notes so far: https://gist.github.com/304a952e0b171d1b38b351db9514b12f

**Comment by TomAugspurger** [comment]
Upgraded ocean, hydro, and dev now.

@tjcrone you'll need to update ooi I think. The process should be roughly

1. Install helm3 (I'm using 3.0.3. 3.1 was released 1 hour ago). I'm using `/usr/local/bin/helm3` rather than `helm`. Will alias it later
2. Install hubploy master: pip install -U git+https://github.com/yuvipanda/hubploy (with https://github.com/yuvipanda/hubploy/commit/7c2f17389c27ee29582f2be005dfd6b3ab2d8db0)

then

```
# install 2to3 plugin
helm3 plugin install https://github.com/helm/helm-2to3

# update config
helm3 2to3 move config --dry-run

# after verifying
helm3 2to3 move config

# check
helm3 repo list

# convert
helm3 2to3 convert ooi-staging

# redeploy
HELM_EXECUTABLE=/usr/local/bin/helm3 hubploy deploy ooi pangeo-deploy staging 
# that may error. If so

kubectl get deployment/gateway-ooi-staging-dask-gateway -n ooi-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
kubectl get deployment/scheduler-proxy-ooi-staging-dask-gateway -n ooi-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
kubectl get deployment/web-proxy-ooi-staging-dask-gateway -n ooi-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -

HELM_EXECUTABLE=/usr/local/bin/helm3 hubploy deploy hydro pangeo-deploy staging 
```

Then we're hopefully good to go.

**Comment by tjcrone** [comment]
Wow thanks @TomAugspurger. I am going through your steps and I think we are close! helm 3.0.3 is the default so I'm not using the environment variable. ran through the three kubectl lines which worked great. On the last hubploy, got this:
```
Merged "ooi-pangeo" as current context in /Users/tjc/.kube/config
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: open /Users/tjc/Library/Caches/helm/repository/local-index.yaml: no such file or directory
Traceback (most recent call last):
  File "/Users/tjc/miniconda3/envs/pangeo-deploy/bin/hubploy", line 8, in <module>
    sys.exit(main())
  File "/Users/tjc/miniconda3/envs/pangeo-deploy/lib/python3.7/site-packages/hubploy/__main__.py", line 89, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force)
  File "/Users/tjc/miniconda3/envs/pangeo-deploy/lib/python3.7/site-packages/hubploy/helm.py", line 129, in deploy
    force
  File "/Users/tjc/miniconda3/envs/pangeo-deploy/lib/python3.7/site-packages/hubploy/helm.py", line 47, in helm_upgrade
    ], cwd=chart)
  File "/Users/tjc/miniconda3/envs/pangeo-deploy/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'dep', 'up']' returned non-zero exit status 1.
```

**Comment by tjcrone** [comment]
Using this version of hubploy: `pip install -U git+https://github.com/yuvipanda/hubploy@1767689c5277400a473b9f239a851f75051d8240`

**Comment by TomAugspurger** [comment]
Oh, I saw that too... One sec.

**Comment by TomAugspurger** [comment]
@tjcrone I had to do `helm3 repo remove local` to fix that. I have no idea what the local repo is used for (testing?) or how to restore it. Hopefully not too destructive.

**Comment by tjcrone** [comment]
@TomAugspurger thank you, that worked! OOI staging is now on helm 3, and if I understand correctly, so are the GKE deployments. This is really fantastic. We really appreciate your help on this.

I guess all we need to do now is fix up the CI on pangeo-cloud-federation. Is that right? Is it as simple as changing the helm version here? https://github.com/pangeo-data/pangeo-cloud-federation/blob/b01e267bdb1e8be6249e442c3c61430c120f6fd6/.circleci/config.yml#L229

**Comment by TomAugspurger** [comment]
I hope so :) PR incoming.

**Comment by tjcrone** [comment]
Great! Another thing we may need to change is the version of hubploy in requirements.txt. @yuvipanda's [revert](https://github.com/yuvipanda/hubploy/pull/50) hasn't been merged, so I could not use the latest commit on master. Not sure which one is best at this stage. Possibly https://github.com/yuvipanda/hubploy/commit/1767689c5277400a473b9f239a851f75051d8240.

**Comment by tjcrone** [comment]
@TomAugspurger your updates worked great for staging! Thank you very much. This is exciting. Do we need to go through the same steps by hand for prod before we merge there?

**Comment by TomAugspurger** [comment]
I believe so. Do you want to do that now, or see how things are on staging for a bit?

**Comment by tjcrone** [comment]
Well, I just went through the process by hand on OOI prod, and it is working fine. So we are on helm3 over there so I think a merge to prod would work for us. We don't have nearly as many users so lower risk.

I am not in a position to make a decision for ocean prod, but I'm happy to take your advice on this. Would you recommend that we wait a while? Might make sense to at least wait for @jhamman to weigh in. I think he might be offline so far today. @scottyhq may also have thoughts.

**Comment by TomAugspurger** [comment]
I'll go ahead and do it for prod so that we're consistent.

**Comment by scottyhq** [comment]
I'm in favor of doing this since it would make it easier to get the AWS hubs back up to date in this repo! Thanks @TomAugspurger and @tjcrone

**Comment by TomAugspurger** [comment]
Migrated dev-prod, ocean-prod, and hydro-prod. I think we're good to merge staging into prod & hopefully everything will be green.

I have to run for a bit but will check in later today.

The last thing would be to clean up the old data: https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/#clean-up-of-helm-v2-data. Perhaps we do that tomorrow or next week, in case we need to roll back.

**Comment by tjcrone** [comment]
Okay I merged to prod and it worked! Everyone is back to green. Thank you very much @TomAugspurger.
