### ISSUE TITLE
Staging deployments failing

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#588]
https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1075/workflows/2f0e65dd-bed5-4699-93d8-4cae21d93900/jobs/1220

```
Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1", unable to recognize "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"]
 
Traceback (most recent call last):
 
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
 
    load_entry_point('hubploy==0.1.0', 'console_scripts', 'hubploy')()
 
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 102, in main
 
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force, args.atomic, args.cleanup_on_fail)
 
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 161, in deploy
 
    cleanup_on_fail
 
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 93, in helm_upgrade
 
    subprocess.check_call(cmd)
 
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
 
    raise CalledProcessError(retcode, cmd)
 
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'dev-staging', 'dev-staging', 'pangeo-deploy', '--cleanup-on-fail', '-f', 'deployments/dev/config/common.yaml', '-f', 'deployments/dev/config/staging.yaml', '-f', 'deployments/dev/secrets/staging.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=5005363d', '--set', 'pangeo.jupyterhub.singleuser.image.name=gcr.io/*************/dev-pangeo-io-notebook']' returned non-zero exit status 1.
 
```

**Comment by TomAugspurger** [comment]
Maybe fixed after https://github.com/pangeo-data/pangeo-cloud-federation/pull/589 is merged.

**Comment by TomAugspurger** [comment]
#589 apparently didn't work. Looking more later today.

**Comment by TomAugspurger** [comment]
#591 apparently fixed things. Might want to test out staging a bit just to confirm.
