### ISSUE TITLE
GCP cluster not starting Jupyter sessions

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#695]
Both staging and prod seem to be hanging when I request a singleuser server. IIUC, the server seems to be ready (this is the `jupyter-tomaugspurger` pod

```
[I 2020-08-18 14:33:15.092 SingleUserNotebookApp extension:158] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2020-08-18 14:33:15.092 SingleUserNotebookApp extension:159] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 2020-08-18 14:33:15.106 SingleUserNotebookApp singleuser:561] Starting jupyterhub-singleuser server version 1.1.0
[I 2020-08-18 14:33:15.116 SingleUserNotebookApp notebookapp:1924] Serving notebooks from local directory: /home/jovyan
[I 2020-08-18 14:33:15.116 SingleUserNotebookApp notebookapp:1924] The Jupyter Notebook is running at:
[I 2020-08-18 14:33:15.116 SingleUserNotebookApp notebookapp:1924] http://jupyter-tomaugspurger:8888/user/tomaugspurger/
[I 2020-08-18 14:33:15.116 SingleUserNotebookApp notebookapp:1925] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2020-08-18 14:33:15.138 SingleUserNotebookApp singleuser:542] Updating Hub with activity every 300 seconds
```

but the hub apparently doesn't see it. I do see this in the hub's logs

```
[I 2020-08-18 13:06:59.177 JupyterHub log:174] 200 GET /hub/health (@10.36.2.1) 0.72ms
2020-08-18 13:07:00,379 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57c374e0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57c374e0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-18 13:07:00,380 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57e75a58>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57e75a58>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-18 13:07:00,381 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57e75908>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57e75908>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
[E 2020-08-18 13:07:00.382 JupyterHub reflector:265] Error when watching resources, retrying in 25.6s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/reflector.py", line 206, in _watch_and_update
        resource_version = self._list_and_update()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/reflector.py", line 157, in _list_and_update
        _request_timeout=self.request_timeout,
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 355, in request
        headers=headers)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 231, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 205, in request
        headers=headers)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 76, in request
        method, url, fields=fields, headers=headers, **urlopen_kw
      File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 97, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.39.240.1', port=443): Max retries exceeded with url: /api/v1/namespaces/prod/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b57e759b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

But I'm not sure if it's related right now.

And eventually

```
[E 2020-08-18 14:37:40.789 JupyterHub spawner:1836] Pod jupyter-tomaugspurger never showed up in reflector, restarting pod reflector
[I 2020-08-18 14:37:40.796 JupyterHub reflector:199] watching for pods with label selector='component=singleuser-server' in namespace staging
[E 2020-08-18 14:37:40.796 JupyterHub gen:599] Exception in Future <Future finished exception=TimeoutError('pod/jupyter-tomaugspurger did not start in 600 seconds!',)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1828, in _start
        timeout=self.start_timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-tomaugspurger did not start in 600 seconds!
```

**Comment by TomAugspurger** [comment]
Ah, apparently jupyterhub self-restarting the reflect was all that was needed (Asking for another server in staging gave me one right away). I'll see if the same happens for prod.

**Comment by TomAugspurger** [comment]
Seems to be OK now. Let me know if anyone else runs into problems.
