### ISSUE TITLE
CircleCI failures

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#893]
After merging https://github.com/pangeo-data/pangeo-cloud-federation/pull/891, we're getting the following errors for GCP and OOI in circleCI (https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1640/workflows/59c29861-86ba-4e27-9ca4-11a1e8d85257/jobs/1807)

cc @tjcrone @TomAugspurger 

```
#!/bin/bash -eo pipefail
hubploy build gcp-uscentral1b --check-registry --push
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/circleci/repo/venv/lib/python3.7/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/circleci/repo/venv/lib/python3.7/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by TomAugspurger** [comment]
pip just released a version with their new resolver. I wonder if that's related. This error seems to be coming from hubploy (cc @yuvipanda).

For now we could try pinning pip<20.3 in the circleCI env.

**Comment by tjcrone** [comment]
+1 on pinning pip.

**Comment by tjcrone** [comment]
May not be due to the new pip resolver. I noticed this in the install dependencies step:
```
requests 2.24.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.2 which is incompatible.
Installing collected packages: requests, pygithub, botocore, awscli, boto3, hubploy
  Found existing installation: requests 2.25.0
    Uninstalling requests-2.25.0:
      Successfully uninstalled requests-2.25.0
  Found existing installation: PyGithub 1.53
    Uninstalling PyGithub-1.53:
      Successfully uninstalled PyGithub-1.53
  Found existing installation: botocore 1.19.22
    Uninstalling botocore-1.19.22:
      Successfully uninstalled botocore-1.19.22
  Found existing installation: awscli 1.18.182
    Uninstalling awscli-1.18.182:
      Successfully uninstalled awscli-1.18.182
  Found existing installation: boto3 1.16.22
    Uninstalling boto3-1.16.22:
      Successfully uninstalled boto3-1.16.22
  Found existing installation: hubploy 0.1.0
    Uninstalling hubploy-0.1.0:
      Successfully uninstalled hubploy-0.1.0
  Running setup.py install for hubploy ... - done
Successfully installed awscli-1.18.185 boto3-1.16.25 botocore-1.19.25 hubploy-0.1.0 pygithub-1.54 requests-2.24.0
You are using pip version 18.1, however version 20.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CircleCI received exit code 0
```
Did we pin requests?

**Comment by tjcrone** [comment]
Actually pygithub pins requests to <2.25, which is incompatible with urllib3 1.26.2:
```
Collecting requests<2.25,>=2.14.0 (from pygithub->-r requirements.txt (line 3))
```
Pinning urllib3 back for now might be a quick temporary fix.

**Comment by tjcrone** [comment]
This is a recent change in pygithub: https://github.com/PyGithub/PyGithub/commit/d159425f36dc7f68766cc980e262e9287e5f111c.

**Comment by tjcrone** [comment]
PyGithub has reverted this pin but it has not been merged (https://github.com/PyGithub/PyGithub/pull/1763). I think pinning urllib3 back for now is the right fix for us for now.
